theme: jekyll-theme-minimal
title: Friedhofsregister der jüdischen Gemeinde zu Strelitz. [s. l.], 1923.
description: Auf diesen Seiten finden sich alle relevanten Daten (ALTO/TEI/images) zum jüdischen Friedhofsregister der Strelitzer Gemeinde in Mecklenburg.
