theme: jekyll-theme-minimal
title: Friedhofsregister der jüdischen Gemeinde zu Strelitz (1740–1923)
description: Hier finden sich alle Informationen über den Digitalisierungsprozess des Friedhofregisters der jüdischen Gemeinde zu Strelitz. Im zugehörigen Repositorium befinden sich alle relevanten Daten. Alle Daten stehen unter der Lizenz CC BY-SA 4. Kontakt: sebastian.goettel(at)bbaw.de
