theme: jekyll-theme-minimal
title: Friedhofsregister der jüdischen Gemeinde zu Strelitz (1740–1923)
description: In diesem Repositorium befinden sich alle relevanten Daten zum Friedhofsregister der jüdischen Gemeinde zu Strelitz sowie alle Informationen über den Digitalisierungsprozess
