title: Friedhofsregister Strelitz
logo: /assets/img/logo.png
description: Friedhofsregister der jüdischen Gemeinde zu Strelitz (1740–1923). Alle verfügbaren Daten stehen unter der Lizenz CC BY-SA 4.0
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
